name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.3
    with:
      working_directory: './examples/basic/'

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.3
    with:
      working_directory: './examples/complete/'

  nsg-with-flow-logs-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.3
    with:
      working_directory: './examples/nsg-with-flow-logs/'
