name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './_example/basic/'

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './_example/complete/'

  nsg-with-flow-logs-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './_example/nsg-with-flow-logs/'
